import "dotenv/config";
import { prisma } from "../src/lib/prisma";
import type {
  BuildingType,
  CadastralClass,
  DevelopmentPotential,
  LandUse,
  PlanningStatus,
  PlotShape,
  Topography,
} from "../src/generated/prisma/enums";

function slugify(title: string, ref: string) {
  return (
    title
      .toLowerCase()
      .normalize("NFD")
      .replace(/[̀-ͯ]/g, "")
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "") +
    "-" +
    ref.slice(-6).toLowerCase()
  );
}

function rectangleAround(lat: number, lng: number, halfSideMeters: number) {
  const dLat = halfSideMeters / 111_320;
  const dLng = halfSideMeters / (111_320 * Math.cos((lat * Math.PI) / 180));
  return {
    type: "Polygon",
    coordinates: [
      [
        [lng - dLng, lat - dLat],
        [lng + dLng, lat - dLat],
        [lng + dLng, lat + dLat],
        [lng - dLng, lat + dLat],
        [lng - dLng, lat - dLat],
      ],
    ],
  };
}

interface SeedPlot {
  title: string;
  referenciaCatastral: string;
  address: string;
  municipality: string;
  province: string;
  autonomousCommunity: string;
  postalCode: string;
  latitude: number;
  longitude: number;
  description: string;
  plotSize: number;
  builtArea?: number;
  superficieGrafica?: number;
  constructionYear?: number;
  landUse: LandUse;
  cadastralUse: CadastralClass;
  buildingType: BuildingType;
  numberOfFloors?: number;
  maxBuildableArea: number;
  buildabilityRatio: number;
  occupancyRatio: number;
  plotShape: PlotShape;
  cornerPlot?: boolean;
  frontageWidth: number;
  depth: number;
  planningStatus: PlanningStatus;
  developmentPotential: DevelopmentPotential[];
  allowedUses: string[];
  maxHeight?: number;
  restrictions?: string[];
  zoning?: string;
  purchasePrice: number;
  estimatedConstructionCost?: number;
  expectedROI?: number;
  expectedYield?: number;
  developmentMargin?: number;
  topography: Topography;
  doubleFrontage?: boolean;
  existingBuilding?: boolean;
  demolitionRequired?: boolean;
  vacantLand?: boolean;
  nearbyAmenities?: string[];
}

const RAW_PLOTS: SeedPlot[] = [
  {
    title: "Solar edificable en Chamberí",
    referenciaCatastral: "9872023VK4797S0001WX",
    address: "Calle de Fuencarral 142",
    municipality: "Madrid",
    province: "Madrid",
    autonomousCommunity: "Comunidad de Madrid",
    postalCode: "28010",
    latitude: 40.4327,
    longitude: -3.7028,
    description:
      "Solar urbano vacante en el corazon de Chamberi, ideal para promocion residencial plurifamiliar de alto standing con posibilidad de local comercial en planta baja.",
    plotSize: 620,
    builtArea: 0,
    superficieGrafica: 615,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 2170,
    buildabilityRatio: 3.5,
    occupancyRatio: 70,
    plotShape: "RECTANGULAR",
    cornerPlot: true,
    frontageWidth: 22,
    depth: 28,
    planningStatus: "URBAN",
    developmentPotential: ["RESIDENTIAL", "MIXED_USE"],
    allowedUses: ["Residencial", "Terciario en planta baja"],
    maxHeight: 24,
    restrictions: ["Altura maxima 7 plantas", "Proteccion de fachada catalogada en edificio colindante"],
    zoning: "PGOUM 1997 - Normativa Zona 1 Grado 3",
    purchasePrice: 3_950_000,
    estimatedConstructionCost: 5_800_000,
    expectedROI: 22.5,
    expectedYield: 6.1,
    developmentMargin: 18.4,
    topography: "FLAT",
    doubleFrontage: true,
    vacantLand: true,
    nearbyAmenities: ["Metro Quevedo 350m", "Colegio San Ignacio 200m", "Parque Santander 400m"],
  },
  {
    title: "Parcela terciaria en 22@ Poblenou",
    referenciaCatastral: "1234567DF3812N0002RT",
    address: "Carrer de Pere IV 220",
    municipality: "Barcelona",
    province: "Barcelona",
    autonomousCommunity: "Cataluña",
    postalCode: "08005",
    latitude: 41.4038,
    longitude: 2.1934,
    description:
      "Parcela en el distrito de innovacion 22@, apta para hotel, aparthotel o edificio de oficinas de alta gama junto al frente maritimo digital.",
    plotSize: 1450,
    builtArea: 0,
    superficieGrafica: 1442,
    landUse: "COMMERCIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 7250,
    buildabilityRatio: 5.0,
    occupancyRatio: 80,
    plotShape: "REGULAR",
    frontageWidth: 38,
    depth: 40,
    planningStatus: "URBAN",
    developmentPotential: ["HOTEL", "APARTHOTEL", "OFFICE"],
    allowedUses: ["22@ Actividades @", "Hotelero", "Terciario"],
    maxHeight: 45,
    restrictions: ["Cesion 10% para equipamiento", "Certificacion energetica A obligatoria"],
    zoning: "MPGM 22@ Poblenou",
    purchasePrice: 12_500_000,
    estimatedConstructionCost: 21_000_000,
    expectedROI: 19.8,
    expectedYield: 7.4,
    developmentMargin: 16.2,
    topography: "FLAT",
    vacantLand: true,
    nearbyAmenities: ["Metro Llacuna 180m", "Playa del Bogatell 900m", "Tram T4 300m"],
  },
  {
    title: "Suelo urbanizable residencial en Malilla",
    referenciaCatastral: "5566778VH5900S0003ZX",
    address: "Camino de Malilla 45",
    municipality: "Valencia",
    province: "Valencia",
    autonomousCommunity: "Comunidad Valenciana",
    postalCode: "46026",
    latitude: 39.4462,
    longitude: -0.3891,
    description:
      "Suelo urbanizable ordenado sector Malilla Sur, previsto para desarrollo residencial plurifamiliar con dotacion de zonas verdes ya urbanizadas.",
    plotSize: 3200,
    builtArea: 0,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 5760,
    buildabilityRatio: 1.8,
    occupancyRatio: 45,
    plotShape: "IRREGULAR",
    frontageWidth: 60,
    depth: 53,
    planningStatus: "DEVELOPABLE",
    developmentPotential: ["RESIDENTIAL"],
    allowedUses: ["Residencial plurifamiliar", "Vivienda protegida (30%)"],
    maxHeight: 21,
    restrictions: ["30% VPO obligatorio", "Reparcelacion pendiente de finalizar"],
    zoning: "PAI Sector Malilla Sur",
    purchasePrice: 4_200_000,
    estimatedConstructionCost: 8_100_000,
    expectedROI: 24.1,
    expectedYield: 6.8,
    developmentMargin: 19.9,
    topography: "FLAT",
    vacantLand: true,
    nearbyAmenities: ["Estacion Joaquin Sorolla 1.2km", "Bioparc 2km"],
  },
  {
    title: "Parcela hotelera frente al mar en Malagueta",
    referenciaCatastral: "3344556UF6612N0004MG",
    address: "Paseo de la Farola 8",
    municipality: "Málaga",
    province: "Málaga",
    autonomousCommunity: "Andalucía",
    postalCode: "29016",
    latitude: 36.7169,
    longitude: -4.4034,
    description:
      "Parcela hotelera en primera linea de playa de la Malagueta, con vistas directas al Mediterraneo, apta para hotel 5 estrellas o aparthotel de lujo.",
    plotSize: 1800,
    builtArea: 950,
    constructionYear: 1968,
    landUse: "TOURISM",
    cadastralUse: "URBANO",
    buildingType: "HOTEL_BUILDING",
    numberOfFloors: 4,
    maxBuildableArea: 6300,
    buildabilityRatio: 3.5,
    occupancyRatio: 60,
    plotShape: "RECTANGULAR",
    cornerPlot: true,
    frontageWidth: 45,
    depth: 40,
    planningStatus: "URBAN",
    developmentPotential: ["HOTEL", "APARTHOTEL"],
    allowedUses: ["Hotelero", "Terciario turistico"],
    maxHeight: 32,
    restrictions: ["Servidumbre de proteccion de costas", "Retranqueo obligatorio 20m desde ribera"],
    zoning: "PGOU Malaga - Uso Turistico T1",
    purchasePrice: 18_900_000,
    estimatedConstructionCost: 14_500_000,
    expectedROI: 21.3,
    expectedYield: 8.2,
    developmentMargin: 15.6,
    topography: "FLAT",
    existingBuilding: true,
    demolitionRequired: true,
    nearbyAmenities: ["Playa Malagueta 0m", "Centro historico 900m", "Puerto de Malaga 1.1km"],
  },
  {
    title: "Villa de lujo con parcela ampliable en la Milla de Oro",
    referenciaCatastral: "7788990XE9723S0005MB",
    address: "Urbanizacion Sierra Blanca, Parcela 12",
    municipality: "Marbella",
    province: "Málaga",
    autonomousCommunity: "Andalucía",
    postalCode: "29602",
    latitude: 36.5223,
    longitude: -4.9203,
    description:
      "Parcela residencial en Sierra Blanca con villa existente para reforma o sustitucion, orientacion sur y vistas al mar, en la exclusiva Milla de Oro.",
    plotSize: 2500,
    builtArea: 680,
    constructionYear: 1995,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "VILLA",
    numberOfFloors: 2,
    maxBuildableArea: 1000,
    buildabilityRatio: 0.4,
    occupancyRatio: 25,
    plotShape: "IRREGULAR",
    frontageWidth: 50,
    depth: 55,
    planningStatus: "URBAN",
    developmentPotential: ["RESIDENTIAL"],
    allowedUses: ["Vivienda unifamiliar aislada"],
    maxHeight: 9,
    restrictions: ["Proteccion paisajistica de laderas"],
    zoning: "PGOU Marbella - Suelo Urbano Residencial Baja Densidad",
    purchasePrice: 9_800_000,
    estimatedConstructionCost: 3_200_000,
    expectedROI: 14.2,
    expectedYield: 3.9,
    developmentMargin: 12.1,
    topography: "SLOPED",
    existingBuilding: true,
    nearbyAmenities: ["Puerto Banus 3km", "Colegio internacional 1.5km", "Campo de golf 800m"],
  },
  {
    title: "Casa palacio protegida en el Casco Antiguo",
    referenciaCatastral: "2233445TG3399N0006SV",
    address: "Calle Mateos Gago 15",
    municipality: "Sevilla",
    province: "Sevilla",
    autonomousCommunity: "Andalucía",
    postalCode: "41004",
    latitude: 37.3858,
    longitude: -5.9917,
    description:
      "Inmueble catalogado junto a la Catedral de Sevilla con fachada protegida, oportunidad de rehabilitacion para boutique hotel o residencial exclusivo.",
    plotSize: 480,
    builtArea: 890,
    constructionYear: 1890,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "APARTMENT_BLOCK",
    numberOfFloors: 3,
    maxBuildableArea: 960,
    buildabilityRatio: 2.0,
    occupancyRatio: 85,
    plotShape: "IRREGULAR",
    frontageWidth: 12,
    depth: 40,
    planningStatus: "HISTORIC",
    developmentPotential: ["HOTEL", "RESIDENTIAL"],
    allowedUses: ["Residencial", "Hotelero boutique"],
    maxHeight: 14,
    restrictions: ["Nivel de proteccion integral (BIC entorno Catedral)", "Fachada y patio interior catalogados"],
    zoning: "PEPCH Casco Historico Sevilla",
    purchasePrice: 3_400_000,
    estimatedConstructionCost: 2_900_000,
    expectedROI: 17.5,
    expectedYield: 5.4,
    developmentMargin: 13.8,
    topography: "FLAT",
    existingBuilding: true,
    nearbyAmenities: ["Catedral de Sevilla 80m", "Barrio Santa Cruz 150m"],
  },
  {
    title: "Nave logistica junto a la AP-7",
    referenciaCatastral: "8899001PL0456S0007AL",
    address: "Poligono Industrial Las Atalayas, Parcela 34",
    municipality: "Alicante",
    province: "Alicante",
    autonomousCommunity: "Comunidad Valenciana",
    postalCode: "03114",
    latitude: 38.3745,
    longitude: -0.5228,
    description:
      "Parcela industrial con acceso directo a la autopista AP-7, ideal para plataforma logistica de ultima milla o centro de distribucion.",
    plotSize: 9500,
    builtArea: 4200,
    constructionYear: 2004,
    landUse: "INDUSTRIAL",
    cadastralUse: "URBANO",
    buildingType: "WAREHOUSE",
    numberOfFloors: 1,
    maxBuildableArea: 6650,
    buildabilityRatio: 0.7,
    occupancyRatio: 70,
    plotShape: "REGULAR",
    frontageWidth: 95,
    depth: 100,
    planningStatus: "URBAN",
    developmentPotential: ["LOGISTICS"],
    allowedUses: ["Industrial", "Almacenaje y distribucion"],
    maxHeight: 12,
    restrictions: ["Limite de ocupacion 70%"],
    zoning: "PGOU Alicante - Suelo Industrial",
    purchasePrice: 5_100_000,
    estimatedConstructionCost: 1_800_000,
    expectedROI: 16.9,
    expectedYield: 7.9,
    developmentMargin: 14.3,
    topography: "FLAT",
    existingBuilding: true,
    nearbyAmenities: ["Acceso AP-7 400m", "Aeropuerto Alicante-Elche 8km"],
  },
  {
    title: "Finca rustica con potencial turistico en Sant Josep",
    referenciaCatastral: "0011223IB7788S0008IB",
    address: "Cami de Cala Tarida s/n",
    municipality: "Sant Josep de sa Talaia",
    province: "Islas Baleares",
    autonomousCommunity: "Islas Baleares",
    postalCode: "07830",
    latitude: 38.9345,
    longitude: 1.2278,
    description:
      "Finca rustica de gran extension cerca de Cala Tarida, terreno virgen con posibilidad de vivienda unifamiliar aislada sujeta a normativa rural.",
    plotSize: 21000,
    builtArea: 0,
    landUse: "AGRICULTURAL",
    cadastralUse: "RUSTICO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 420,
    buildabilityRatio: 0.02,
    occupancyRatio: 2,
    plotShape: "IRREGULAR",
    frontageWidth: 140,
    depth: 150,
    planningStatus: "RURAL",
    developmentPotential: ["RESIDENTIAL"],
    allowedUses: ["Vivienda unifamiliar aislada vinculada a explotacion agraria"],
    restrictions: ["Suelo rustico protegido (ANEI colindante)", "Parcela minima edificable 20.000m2"],
    zoning: "PTI Ibiza - Suelo Rustico Protegido",
    purchasePrice: 6_200_000,
    estimatedConstructionCost: 950_000,
    expectedROI: 11.4,
    expectedYield: 3.1,
    developmentMargin: 9.8,
    topography: "SLOPED",
    vacantLand: true,
    nearbyAmenities: ["Cala Tarida 1.8km", "Ibiza ciudad 14km"],
  },
  {
    title: "Edificio de oficinas en Abandoibarra",
    referenciaCatastral: "4455667BI2233N0009BI",
    address: "Alameda Rekalde 42",
    municipality: "Bilbao",
    province: "Vizcaya",
    autonomousCommunity: "País Vasco",
    postalCode: "48009",
    latitude: 43.2601,
    longitude: -2.9349,
    description:
      "Edificio de oficinas junto al distrito financiero de Abandoibarra, candidato a reposicionamiento integral o cambio de uso a residencial.",
    plotSize: 950,
    builtArea: 3800,
    constructionYear: 1978,
    landUse: "COMMERCIAL",
    cadastralUse: "URBANO",
    buildingType: "OFFICE_BUILDING",
    numberOfFloors: 6,
    maxBuildableArea: 4275,
    buildabilityRatio: 4.5,
    occupancyRatio: 90,
    plotShape: "RECTANGULAR",
    frontageWidth: 28,
    depth: 34,
    planningStatus: "URBAN",
    developmentPotential: ["OFFICE", "RESIDENTIAL"],
    allowedUses: ["Terciario oficinas", "Residencial (cambio de uso sujeto a licencia)"],
    maxHeight: 26,
    restrictions: ["Cambio de uso requiere informe de compatibilidad urbanistica"],
    zoning: "PGOU Bilbao - Zona Abandoibarra",
    purchasePrice: 7_600_000,
    estimatedConstructionCost: 4_100_000,
    expectedROI: 18.2,
    expectedYield: 6.5,
    developmentMargin: 15.0,
    topography: "FLAT",
    existingBuilding: true,
    nearbyAmenities: ["Museo Guggenheim 600m", "Metro Moyua 350m"],
  },
  {
    title: "Solar senior living junto al Paseo Maritimo",
    referenciaCatastral: "6677889PM4455N0010PM",
    address: "Avenida Joan Miro 88",
    municipality: "Palma de Mallorca",
    province: "Islas Baleares",
    autonomousCommunity: "Islas Baleares",
    postalCode: "07015",
    latitude: 39.5528,
    longitude: 2.6208,
    description:
      "Solar urbano junto al Paseo Maritimo de Palma, orientado a residencia de mayores o senior living con vistas a la Bahia de Palma.",
    plotSize: 2100,
    builtArea: 0,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 4200,
    buildabilityRatio: 2.0,
    occupancyRatio: 55,
    plotShape: "REGULAR",
    frontageWidth: 42,
    depth: 50,
    planningStatus: "URBAN",
    developmentPotential: ["SENIOR_LIVING", "RESIDENTIAL"],
    allowedUses: ["Residencial", "Equipamiento asistencial"],
    maxHeight: 18,
    restrictions: ["Reserva de plazas de aparcamiento 1/50m2"],
    zoning: "PGOU Palma - Zona Bahia",
    purchasePrice: 6_900_000,
    estimatedConstructionCost: 7_400_000,
    expectedROI: 20.6,
    expectedYield: 7.1,
    developmentMargin: 17.2,
    topography: "FLAT",
    vacantLand: true,
    nearbyAmenities: ["Paseo Maritimo 50m", "Hospital Son Espases 4km"],
  },
  {
    title: "Plataforma logistica en Plaza PLAZA",
    referenciaCatastral: "3322110ZA6677N0011ZA",
    address: "Plataforma Logistica PLAZA, Parcela C-14",
    municipality: "Zaragoza",
    province: "Zaragoza",
    autonomousCommunity: "Aragón",
    postalCode: "50197",
    latitude: 41.6853,
    longitude: -0.9897,
    description:
      "Parcela en la plataforma logistica PLAZA, uno de los mayores hubs logisticos de Europa, con conexion directa a la red ferroviaria y AP-68.",
    plotSize: 15000,
    builtArea: 0,
    landUse: "INDUSTRIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 9000,
    buildabilityRatio: 0.6,
    occupancyRatio: 65,
    plotShape: "REGULAR",
    frontageWidth: 120,
    depth: 125,
    planningStatus: "URBAN",
    developmentPotential: ["LOGISTICS"],
    allowedUses: ["Logistico", "Industrial ligero"],
    maxHeight: 15,
    restrictions: ["Altura maxima nave 15m", "Reserva viales internos"],
    zoning: "PGOU Zaragoza - Sector PLAZA",
    purchasePrice: 6_750_000,
    estimatedConstructionCost: 5_200_000,
    expectedROI: 19.4,
    expectedYield: 8.6,
    developmentMargin: 16.8,
    topography: "FLAT",
    vacantLand: true,
    nearbyAmenities: ["Terminal ferroviaria PLAZA 1km", "Aeropuerto de Zaragoza 3km"],
  },
  {
    title: "Residencia de estudiantes junto al Campus de Fuentenueva",
    referenciaCatastral: "5544332GR8899N0012GR",
    address: "Calle Real de Cartuja 60",
    municipality: "Granada",
    province: "Granada",
    autonomousCommunity: "Andalucía",
    postalCode: "18011",
    latitude: 37.1953,
    longitude: -3.6087,
    description:
      "Parcela a 5 minutos del Campus de Fuentenueva de la Universidad de Granada, alta demanda estructural de alojamiento estudiantil (PBSA).",
    plotSize: 1650,
    builtArea: 0,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 4950,
    buildabilityRatio: 3.0,
    occupancyRatio: 75,
    plotShape: "RECTANGULAR",
    frontageWidth: 33,
    depth: 50,
    planningStatus: "URBAN",
    developmentPotential: ["STUDENT_HOUSING", "RESIDENTIAL"],
    allowedUses: ["Residencial", "Equipamiento docente-residencial"],
    maxHeight: 20,
    purchasePrice: 3_100_000,
    estimatedConstructionCost: 5_900_000,
    expectedROI: 23.7,
    expectedYield: 7.8,
    developmentMargin: 19.1,
    topography: "SLOPED",
    vacantLand: true,
    nearbyAmenities: ["Campus Fuentenueva 400m", "Hospital Virgen de las Nieves 1.2km"],
  },
  {
    title: "Finca agricola con nave en desuso para reconversion",
    referenciaCatastral: "9900112VA1122N0013VA",
    address: "Camino de la Overuela 5",
    municipality: "Valladolid",
    province: "Valladolid",
    autonomousCommunity: "Castilla y León",
    postalCode: "47009",
    latitude: 41.6828,
    longitude: -4.7415,
    description:
      "Finca agricola periurbana con nave agraria obsoleta, pendiente de recalificacion, con potencial a medio plazo para uso logistico o residencial de baja densidad.",
    plotSize: 8000,
    builtArea: 1200,
    constructionYear: 1975,
    landUse: "AGRICULTURAL",
    cadastralUse: "RUSTICO",
    buildingType: "WAREHOUSE",
    numberOfFloors: 1,
    maxBuildableArea: 0,
    buildabilityRatio: 0,
    occupancyRatio: 15,
    plotShape: "IRREGULAR",
    frontageWidth: 80,
    depth: 100,
    planningStatus: "RURAL",
    developmentPotential: ["LOGISTICS", "RESIDENTIAL"],
    allowedUses: ["Agricola", "Pendiente de recalificacion urbanistica"],
    restrictions: ["Sujeto a modificacion de planeamiento", "Sin garantia de recalificacion"],
    zoning: "PGOU Valladolid - Suelo Rustico Comun",
    purchasePrice: 1_450_000,
    estimatedConstructionCost: 3_600_000,
    expectedROI: 15.8,
    expectedYield: 5.2,
    developmentMargin: 12.9,
    topography: "FLAT",
    existingBuilding: true,
    demolitionRequired: true,
    nearbyAmenities: ["Rio Pisuerga 300m", "Ronda interior Valladolid 900m"],
  },
  {
    title: "Chalet de esquina para sustitucion en Gros",
    referenciaCatastral: "1100223SS4455N0014SS",
    address: "Calle Zumalakarregi 20",
    municipality: "San Sebastián",
    province: "Guipúzcoa",
    autonomousCommunity: "País Vasco",
    postalCode: "20002",
    latitude: 43.3208,
    longitude: -1.9707,
    description:
      "Parcela de esquina en el barrio de Gros junto a la playa de la Zurriola, con vivienda unifamiliar a sustituir por edificio plurifamiliar de alto valor.",
    plotSize: 540,
    builtArea: 280,
    constructionYear: 1954,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "DETACHED_HOUSE",
    numberOfFloors: 2,
    maxBuildableArea: 1620,
    buildabilityRatio: 3.0,
    occupancyRatio: 65,
    plotShape: "CORNER",
    cornerPlot: true,
    frontageWidth: 20,
    depth: 27,
    planningStatus: "URBAN",
    developmentPotential: ["RESIDENTIAL"],
    allowedUses: ["Residencial plurifamiliar"],
    maxHeight: 18,
    restrictions: ["Altura maxima 6 plantas", "Retranqueo lateral obligatorio"],
    zoning: "PGOU Donostia - Zona Gros",
    purchasePrice: 4_650_000,
    estimatedConstructionCost: 3_900_000,
    expectedROI: 20.9,
    expectedYield: 6.3,
    developmentMargin: 17.5,
    topography: "FLAT",
    existingBuilding: true,
    demolitionRequired: true,
    doubleFrontage: true,
    nearbyAmenities: ["Playa de la Zurriola 250m", "Kursaal 700m"],
  },
  {
    title: "Suelo urbanizable mixto en Vistalegre",
    referenciaCatastral: "2211334MU5566N0015MU",
    address: "Avenida Juan de Borbon 300",
    municipality: "Murcia",
    province: "Murcia",
    autonomousCommunity: "Región de Murcia",
    postalCode: "30007",
    latitude: 37.9922,
    longitude: -1.1195,
    description:
      "Sector de suelo urbanizable con ordenacion detallada aprobada para uso mixto residencial y terciario, proximo al nuevo hospital de Murcia.",
    plotSize: 5400,
    builtArea: 0,
    landUse: "MIXED",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 8100,
    buildabilityRatio: 1.5,
    occupancyRatio: 50,
    plotShape: "IRREGULAR",
    frontageWidth: 75,
    depth: 72,
    planningStatus: "DEVELOPABLE",
    developmentPotential: ["MIXED_USE", "RESIDENTIAL", "COMMERCIAL"],
    allowedUses: ["Residencial", "Terciario", "Equipamiento privado"],
    maxHeight: 20,
    restrictions: ["Urbanizacion pendiente de recepcion municipal"],
    zoning: "PGOU Murcia - Sector Vistalegre",
    purchasePrice: 5_600_000,
    estimatedConstructionCost: 9_700_000,
    expectedROI: 22.9,
    expectedYield: 7.0,
    developmentMargin: 18.6,
    topography: "FLAT",
    vacantLand: true,
    nearbyAmenities: ["Hospital Virgen de la Arrixaca 2.5km", "Universidad de Murcia 3km"],
  },
  {
    title: "Parcela hotelera en el Paseo Maritimo de El Puerto",
    referenciaCatastral: "3300445CA6677N0016CA",
    address: "Paseo de la Ribera 5",
    municipality: "El Puerto de Santa María",
    province: "Cádiz",
    autonomousCommunity: "Andalucía",
    postalCode: "11500",
    latitude: 36.5966,
    longitude: -6.2308,
    description:
      "Parcela en primera linea de la Bahia de Cadiz, actualmente con antiguo hostal, con potencial para hotel boutique o aparthotel vacacional.",
    plotSize: 1250,
    builtArea: 620,
    constructionYear: 1982,
    landUse: "TOURISM",
    cadastralUse: "URBANO",
    buildingType: "HOTEL_BUILDING",
    numberOfFloors: 3,
    maxBuildableArea: 3125,
    buildabilityRatio: 2.5,
    occupancyRatio: 60,
    plotShape: "RECTANGULAR",
    frontageWidth: 30,
    depth: 42,
    planningStatus: "URBAN",
    developmentPotential: ["HOTEL", "APARTHOTEL"],
    allowedUses: ["Hotelero", "Turistico"],
    maxHeight: 16,
    restrictions: ["Zona de servidumbre de proteccion de costas"],
    zoning: "PGOU El Puerto - Uso Turistico",
    purchasePrice: 4_950_000,
    estimatedConstructionCost: 3_800_000,
    expectedROI: 18.7,
    expectedYield: 7.6,
    developmentMargin: 14.9,
    topography: "FLAT",
    existingBuilding: true,
    demolitionRequired: true,
    nearbyAmenities: ["Playa La Puntilla 150m", "Puerto deportivo 600m"],
  },
  {
    title: "Local comercial y solar en Santa Cruz de Tenerife",
    referenciaCatastral: "4411556TF7788N0017TF",
    address: "Avenida 3 de Mayo 60",
    municipality: "Santa Cruz de Tenerife",
    province: "Santa Cruz de Tenerife",
    autonomousCommunity: "Canarias",
    postalCode: "38005",
    latitude: 28.4682,
    longitude: -16.2546,
    description:
      "Solar comercial en importante eje comercial de Santa Cruz de Tenerife, con alta afluencia peatonal y proximidad al centro administrativo.",
    plotSize: 780,
    builtArea: 0,
    landUse: "COMMERCIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 2340,
    buildabilityRatio: 3.0,
    occupancyRatio: 80,
    plotShape: "RECTANGULAR",
    frontageWidth: 26,
    depth: 30,
    planningStatus: "URBAN",
    developmentPotential: ["COMMERCIAL", "OFFICE"],
    allowedUses: ["Terciario comercial", "Oficinas"],
    maxHeight: 21,
    purchasePrice: 2_650_000,
    estimatedConstructionCost: 2_900_000,
    expectedROI: 19.1,
    expectedYield: 6.9,
    developmentMargin: 15.4,
    topography: "FLAT",
    vacantLand: true,
    nearbyAmenities: ["Auditorio de Tenerife 1.5km", "Zona comercial Meridiano 400m"],
  },
  {
    title: "Suelo urbanizable residencial en Tafira",
    referenciaCatastral: "5522667LP8899N0018LP",
    address: "Carretera del Centro 180",
    municipality: "Las Palmas de Gran Canaria",
    province: "Las Palmas",
    autonomousCommunity: "Canarias",
    postalCode: "35017",
    latitude: 28.0654,
    longitude: -15.4463,
    description:
      "Sector urbanizable en Tafira con vistas a la ciudad y proximidad al campus universitario, planificado para vivienda unifamiliar y plurifamiliar de baja densidad.",
    plotSize: 4100,
    builtArea: 0,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "VACANT_PLOT",
    numberOfFloors: 0,
    maxBuildableArea: 4920,
    buildabilityRatio: 1.2,
    occupancyRatio: 40,
    plotShape: "IRREGULAR",
    frontageWidth: 68,
    depth: 60,
    planningStatus: "DEVELOPABLE",
    developmentPotential: ["RESIDENTIAL"],
    allowedUses: ["Residencial unifamiliar", "Residencial plurifamiliar baja densidad"],
    maxHeight: 12,
    restrictions: ["Pendiente aprobacion definitiva del plan parcial"],
    zoning: "PGO Las Palmas - Sector Tafira",
    purchasePrice: 2_950_000,
    estimatedConstructionCost: 5_100_000,
    expectedROI: 21.6,
    expectedYield: 6.4,
    developmentMargin: 17.8,
    topography: "SLOPED",
    vacantLand: true,
    nearbyAmenities: ["Universidad de Las Palmas 900m", "Jardin Botanico Viera y Clavijo 500m"],
  },
  {
    title: "Casco historico protegido junto al Alcazar",
    referenciaCatastral: "6633778TO9900N0019TO",
    address: "Calle Nuncio Viejo 8",
    municipality: "Toledo",
    province: "Toledo",
    autonomousCommunity: "Castilla-La Mancha",
    postalCode: "45001",
    latitude: 39.8562,
    longitude: -4.0244,
    description:
      "Inmueble en el casco historico Patrimonio de la Humanidad, junto a la Catedral de Toledo, con fuerte proteccion patrimonial y uso potencial turistico-residencial.",
    plotSize: 310,
    builtArea: 540,
    constructionYear: 1920,
    landUse: "RESIDENTIAL",
    cadastralUse: "URBANO",
    buildingType: "APARTMENT_BLOCK",
    numberOfFloors: 3,
    maxBuildableArea: 620,
    buildabilityRatio: 2.0,
    occupancyRatio: 90,
    plotShape: "IRREGULAR",
    frontageWidth: 9,
    depth: 34,
    planningStatus: "HISTORIC",
    developmentPotential: ["RESIDENTIAL", "HOTEL"],
    allowedUses: ["Residencial", "Turistico boutique"],
    maxHeight: 12,
    restrictions: ["BIC - Conjunto Historico de Toledo", "Prohibida alteracion de fachada y cubierta"],
    zoning: "Plan Especial Casco Historico de Toledo",
    purchasePrice: 1_450_000,
    estimatedConstructionCost: 1_100_000,
    expectedROI: 13.9,
    expectedYield: 4.8,
    developmentMargin: 11.2,
    topography: "SLOPED",
    existingBuilding: true,
    nearbyAmenities: ["Catedral de Toledo 120m", "Alcazar de Toledo 300m"],
  },
  {
    title: "Parcela logistica en la Zona Franca de Vigo",
    referenciaCatastral: "7744889VG0011N0020VG",
    address: "Poligono de Balaidos, Parcela 9",
    municipality: "Vigo",
    province: "Pontevedra",
    autonomousCommunity: "Galicia",
    postalCode: "36211",
    latitude: 42.2183,
    longitude: -8.7226,
    description:
      "Parcela industrial junto al puerto de Vigo y la Zona Franca, con excelente conectividad para logistica de componentes de automocion y pesca.",
    plotSize: 6800,
    builtArea: 2100,
    constructionYear: 1998,
    landUse: "INDUSTRIAL",
    cadastralUse: "URBANO",
    buildingType: "WAREHOUSE",
    numberOfFloors: 1,
    maxBuildableArea: 4760,
    buildabilityRatio: 0.7,
    occupancyRatio: 68,
    plotShape: "REGULAR",
    frontageWidth: 85,
    depth: 80,
    planningStatus: "URBAN",
    developmentPotential: ["LOGISTICS"],
    allowedUses: ["Industrial", "Logistico portuario"],
    maxHeight: 14,
    purchasePrice: 3_800_000,
    estimatedConstructionCost: 2_600_000,
    expectedROI: 17.8,
    expectedYield: 8.0,
    developmentMargin: 15.1,
    topography: "FLAT",
    existingBuilding: true,
    nearbyAmenities: ["Puerto de Vigo 2km", "Zona Franca 1km"],
  },
];

async function main() {
  console.log(`Seeding ${RAW_PLOTS.length} plots...`);

  for (const p of RAW_PLOTS) {
    const slug = slugify(p.title, p.referenciaCatastral);
    const pricePerSqm = Math.round((p.purchasePrice / p.plotSize) * 100) / 100;
    const valorCatastral = Math.round(p.purchasePrice * 0.45);

    await prisma.plot.upsert({
      where: { referenciaCatastral: p.referenciaCatastral },
      update: {},
      create: {
        title: p.title,
        slug,
        referenciaCatastral: p.referenciaCatastral,
        address: p.address,
        municipality: p.municipality,
        province: p.province,
        autonomousCommunity: p.autonomousCommunity,
        postalCode: p.postalCode,
        latitude: p.latitude,
        longitude: p.longitude,
        description: p.description,
        plotSize: p.plotSize,
        builtArea: p.builtArea ?? 0,
        superficieGrafica: p.superficieGrafica ?? p.plotSize,
        constructionYear: p.constructionYear,
        landUse: p.landUse,
        cadastralUse: p.cadastralUse,
        buildingType: p.buildingType,
        numberOfFloors: p.numberOfFloors ?? 0,
        maxBuildableArea: p.maxBuildableArea,
        buildabilityRatio: p.buildabilityRatio,
        occupancyRatio: p.occupancyRatio,
        plotShape: p.plotShape,
        cornerPlot: p.cornerPlot ?? false,
        frontageWidth: p.frontageWidth,
        depth: p.depth,
        valorCatastral,
        planningStatus: p.planningStatus,
        developmentPotential: p.developmentPotential,
        allowedUses: p.allowedUses,
        maxHeight: p.maxHeight,
        restrictions: p.restrictions ?? [],
        zoning: p.zoning,
        purchasePrice: p.purchasePrice,
        pricePerSqm,
        estimatedConstructionCost: p.estimatedConstructionCost,
        expectedROI: p.expectedROI,
        expectedYield: p.expectedYield,
        developmentMargin: p.developmentMargin,
        topography: p.topography,
        doubleFrontage: p.doubleFrontage ?? false,
        existingBuilding: p.existingBuilding ?? false,
        demolitionRequired: p.demolitionRequired ?? false,
        vacantLand: p.vacantLand ?? false,
        boundary: rectangleAround(p.latitude, p.longitude, Math.sqrt(p.plotSize) / 2),
        nearbyAmenities: p.nearbyAmenities ?? [],
      },
    });
  }

  console.log("Seed complete.");
}

main()
  .catch((e) => {
    console.error(e);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
